---
title: "Data Manipulation"
output: github_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
```

## Import some data 

I want to import 'FAS_litters.csv'.

```{r}
litters_df = read_csv("data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("data_import_examples/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
```

## Select function 

Let's select some columns 

```{r}
select(litters_df, group, litter_number)
select(litters_df, group, gd0_weight, gd18_weight)

select(litters_df, group, gd0_weight:gd_of_birth)
select(litters_df, group, starts_with("pups"))
# starts_with, ends_with, contains are three useful functions 

select(litters_df, -litter_number)
# can use - to get rid of a specific column

# can also rename columns: 
select(litters_df, GROUP = group, litter_number) # renamed group to GROUP 
rename(litters_df, GROUP = group) # the rename function doesn't do any selecting 

# can rearrange columns using select function
select(litters_df, litter_number, everything())
relocate(litters_df, litter_number)

select(pups_df, litter_number, sex, pd_ears)

# to select only one column:
select(litters_df, group)
# pull(litters_df, group)
```


## Filter

Let's get rid of rows 

```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, group == "Con7")

filter(litters_df, gd0_weight < 23)
## using == and < or > or ! are ways to tell R that we are doing logical operations 

filter(litters_df, pups_survive != 4)
filter(litters_df, !(group == "Con7"))
## != means not equal to 

filter(litters_df, group %in% c("Con7", "Con8"))
## %in% = is in 

## can put together multiple conditions: 
filter(litters_df, group == "Con7", gd_of_birth == 20)

drop_na(litters_df)
drop_na(litters_df, gd0_weight)
```

## Mutate 

Let's add or change columns 

```{r}
mutate(litters_df,
       weight_change = gd18_weight - gd0_weight,
       group = str_to_lower(group))
```

## Arrange 

Let's rearrange the data 

```{r}
arrange(litters_df, desc(gd0_weight))
arrange(litters_df, gd_of_birth, gd0_weight)
```


## Pipes 

```{r}
litters_data_raw = read_csv("data_import_examples/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_select = select(litters_clean_name, group, pups_survive)
litters_filtered = filter(litters_select, group == "Con7")
## ended up here with 4 different lines and 4 different variable names, which is confusing 

## use pipes instead (shift, command, m):
litters_df = 
  read_csv("data_import_examples/FAS_litters.csv") %>% 
  janitor::clean_names() %>%
  select(group, pups_survive) %>% 
  filter(group == "Con7")

litters_df = 
  read_csv("data_import_examples/FAS_litters.csv") %>% 
  janitor::clean_names() %>%
  select(-pups_survive) %>% 
  mutate(
    weight_change = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  ) %>% 
  drop_na(weight_change) %>% 
  filter(group %in% c("con7", "con8")) %>% 
  select(litter_number, group, weight_change, everything())
  
  
```

