---
title: "Simple document"
output: github_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
```

## Import some data 

I want to import 'FAS_litters.csv'.

```{r}
# setting a path to a specific document 
## press tab to get the documents to show up 
litters_df = read_csv("data/FAS_litters.csv")

# don't use absolute paths 
# don't used setwd() 
```

Yay! I imported the dataset. Now I want better names. 

```{r}
names(litters_df) 

litters_df = janitor::clean_names(litters_df)
```

Now I have better names. Let's look at this dataset. 

```{r}
litters_df

head(litters_df)
tail(litters_df)
```

One I use a lot is: 

```{r, eval=FALSE}
# this allows to look at the whole dataframe
view(litters_df)
```

Here's 'skimr':

```{r}
skimr::skim(litters_df)
```


## Arguments in 'read_csv"

```{r}
litters_df = read_csv("data/FAS_litters.csv",
                      skip = 5, 
                      col_names = FALSE,
                      na = "Low8")
```


## Parsing Columns 

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
```


