---
title: "Tidy Data"
author: "Ragyie Rawal"
output: github_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## pivot long 

Load the PULSE data

```{r}
pulse_df = 
  haven::read_sas("data_import_examples/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
```

## pivot wide

now let's try to pivot

```{r}
pulse_tidy = 
  pulse_df %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values = "bdi"
  ) %>%
  mutate(
    visit = replace(visit, vist == "bl", "00m"),
    vist = factor(visit)) %>%
  arrange(id, visit)
```

## pivot_wider

make up a results data table 

```{r}
analysis_df = 
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("a", "b", "a", "b"),
    group_mean = c(4,8,3,6)
  )

analysis_df %>%
  pivot_wider(
    names_from = "time",
    values_from = "group_mean"
  ) %>%
  knitr::kable()
```

## bind rows 

import the LotR movie words dataset 

```{r}
fellowship_df =
  read_excel("data_import_examples/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_rings")

two_towers_df =
  read_excel("data_import_examples/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king_df =
  read_excel("data_import_examples/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
```


## joins 

look at FAS data 

```{r}
litters_df =
  read_csv("data_import_examples/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), 3) %>%
  relocate(litter_number)

pups_df =
  read_csv("data_import_examples/FAS_pups.csv") %>%
  janitor::clean_names() %%
  mutate(sex = record(sex, `1` = "male", `2` = "female"))
```

Let's join these up 

```{r}
fas_df = 
  left_join(pups_df, litters_df, by = "litter_number")
```


